version: "3"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: database-username
      MONGO_INITDB_ROOT_PASSWORD: database-password
    healthcheck:
        test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u database-username -p database-password --quiet | grep 1
        interval: 30s
        timeout: 10s
        retries: 5
    volumes:
      - ./scripts/mongo/init/:/docker-entrypoint-initdb.d
      - ./scripts/mongo/init:/home/mongodb


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: database-username
      ME_CONFIG_MONGODB_ADMINPASSWORD: database-password
      ME_CONFIG_MONGODB_URL: mongodb://database-username:database-password@mongo:27017/

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8000:8000"

