version: "3"
services:
  mongodb-service:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: database-username
      MONGO_INITDB_ROOT_PASSWORD: database-password
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: pass
      MONGODB_DATABASE: database
    healthcheck:
        test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u database-username -p database-password --quiet | grep 1
        interval: 4s
        timeout: 4s
        retries: 5
    volumes:
      - ./scripts/mongo/init/:/docker-entrypoint-initdb.d
      - ./scripts/mongo/init:/home/mongodb
    networks:
      - testnet

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      mongodb-service:
        condition: service_healthy
    links:
      - mongodb-service
    ports:
      - "8000:8000"
    networks:
      - testnet

networks:
  testnet:
    name: custom_workers
